# Generated by Django 4.2 on 2025-05-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_file', models.FileField(upload_to='word_files/')),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('original_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.pdffile')),
            ],
        ),
    ]
